- name: Copy onogrepo file
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/

- name: Install Monogdb
  yum:
    name: mongodb-org
    state: installed
- name: Update monogdb configuration file from listing on 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

