- name: demo on play variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print url
      debug:
        msg: URL = {{ URL }}

- name: demo2 on play variblie2
  hosts: all
  vars:
    URL: www.google.com
  tasks:
    - name: print url2
      debug:
        msg: URL = {{ URL }}

- name: Demo on CLI Variables
  hosts: all
  tasks:
    - name: Print URL1 var from CLI
      debug:
        msg: pusdfdf URL2 = {{ URL2 }}
- name: Demo on cli from  inventory varibels
  hosts: all
  tasks:
    - name: print URL3 varaibles from inventory loc
      debug:
        msg: print inv var URL3 = {{ URL3 }}

- name: Demo variables from a file
  hosts: all
  vars_files:
    - filvar.yml
  tasks:
    - name: Print URL_FILE
      debug:
        msg: URL_FILE = {{ URL_FILE }}

- name: Prompt for input
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}


