- name: demo on play variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print url
      debug:
        msg: URL = {{ URL }}

- name: demo2 on play variblie2
  hosts: all
  vars:
    URL: www.google.com
  tasks:
    - name: print url2
      debug:
        msg: URL = {{ URL }}

- name: demo3
  hosts: all
  tasks:
    -name: print url23
     debug:
       msg: URL = {{ URL2 }}