- name: demo on runtime vars
  hosts: all
  tasks:
    - name: grab uptime
      shell: uptime
      register: OUT

    - name: print uptime
      debug:
        msg: "{{OUT.stdout}}"

    - name: set a variable
      set_fact:
        UPTIME_OUTPUT: "{{ OUT.stdout}}"

    - name: print uptime
      debug:
        msg: "Uptime = {{UPTIME_OUTPUT}}"

