- name: demo on conditions
  hosts: all
  tasks:
    - name: execute if it is centos machine
      debug:
        msg: i am centos
      when: ansible_os_family == "centos"

    - name: excute if debain
      debug:
        msh: Iam debaain
