- name: Setup roboshop project
  hosts: all
  become: yes
  tasks:
    - name: Import Frontend
      ansible.builtin.import_role:
        name: fronend
      tags: fronend
      when: APP == "frontend"
    - name: Import catalogue
      ansible.builtin.import_role:
        name: catalogue
      tags: catalogue
      when: APP == "catalogue"

