- name: Setup Roboshop Project
  hosts: all
  become: yes
  tasks:
    - name: Import Frontend
      #ansible.builtin.import_role:
      import_role:
        name: frontend
      tags:
        - frontend
      #when: APP == "frontend"
    - name: Import catalogue
      #ansible.builtin.import_role:
      import_role:
        name: catalogue
      tags: catalogue
      #when: APP == "catalogue"
